openapi: 3.0.3
info:
  title: ReqRes API - OpenAPI 3.0
  description: API specification for ReqRes service
  version: 1.0.0

servers:
  - url: https://reqres.in/api

tags:
  - name: Users
    description: Operations related to users

paths:
  /users:
    post:
      tags:
        - Users
      summary: Add a new user
      description: Create a new user in the system.
      operationId: addUser
      requestBody:
        description: User details for creation.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '201':
          description: User successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'          
    get:
      tags:
        - Users
      summary: Get users list
      description: Fetches a paginated list of users.
      operationId: getUsers
      parameters:
        - name: page
          in: query
          description: Page number for pagination.
          required: false
          schema:
            type: integer
            example: 1 
      responses:
        '200':
          description: Successfully retrieved users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'

  /users/{id}:
    put:
      tags:
        - Users
      summary: Update an existing user
      description: Updates user information by ID.
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: ID of the user to update.
          required: true
          example: 1
          schema:
            type: integer
      requestBody:
        description: Updated user details.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '200':
          description: Successfully updated user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'  
    delete:
      tags:
        - Users
      summary: Delete a user
      description: Deletes a user by ID.
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: ID of the user to delete.
          required: true
          example: 1
          schema:
            type: integer
      responses:
        '204':
          description: No content - Successfully deleted.

components:
  schemas: 
    UserResponse:
      type: object
      description: Response schema for user data.
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Morpheus"
        job:
          type: string
          example: "Leader"

    UserRequest:
      type: object
      description: Request payload for creating or updating users.
      properties:
        name:
          type: string
          example: "Morpheus"
        job:
          type: string
          example: "Leader"
