openapi: 3.0.3
info:
  title: SDK Example - OpenAPI 3.0
  description: |-
    This spec is meant to demonstrate how to use the SDK generator by readme.io
  version: 1.0.11

servers:
  - url: https://reqres.in/api

tags:
  - name: Users
    description: API operations for users

paths:
  /users:
    post:
      tags:
        - Users
      summary: Add a new user
      description: Add a new user
      operationId: addUser
      requestBody:
        description: User details for creation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userRequest'
        required: true
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'          
    get:
      tags:
        - Users
      summary: Get a list of users
      description: Retrieve a paginated list of users
      operationId: getUsers
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            example: 1 
      responses:
        '200':
          description: Successfully retrieved users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userResponse'

  /users/{id}:
    put:
      tags:
        - Users
      summary: Update an existing user
      description: Update an existing user by ID
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: ID of user to update
          required: true
          example: 1
          schema:
            type: integer
      requestBody:
        description: User details for update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userRequest'
        required: true
      responses:
        '200':
          description: Successfully updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'  
    delete:
      tags:
        - Users
      summary: Delete a user
      description: Delete a user by ID
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: ID of user to delete
          required: true
          example: 1
          schema:
            type: integer
      responses:
        '204':
          description: No content - Successfully deleted

components:
  schemas: 
    userResponse:
      type: object
      description: Response schema for user data
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Morpheus"
        job:
          type: string
          example: "Leader"

    userRequest:
      type: object
      description: Request payload for creating or updating users
      properties:
        name:
          type: string
          example: "Morpheus"
        job:
          type: string
          example: "Leader"
