name: Deploy Swagger UI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Swagger UI
        run: |
          git clone https://github.com/swagger-api/swagger-ui.git
          cp reqres.openapi.yml swagger-ui/dist/swagger.yaml

          # Fix Swagger UI to load reqres.openapi.yml
          cat > swagger-ui/dist/swagger-initializer.js <<EOL
          window.onload = function() {
            window.ui = SwaggerUIBundle({
              url: 'swagger.yaml',
              dom_id: '#swagger-ui',
              deepLinking: true,
              presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
              ],
              layout: "StandaloneLayout"
            });
          };
          EOL

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: swagger-ui/dist
