name: Deploy Swagger UI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Swagger UI
        run: |
          git clone https://github.com/swagger-api/swagger-ui.git
          mkdir -p swagger-ui/dist
          cp reqres.openapi.yml swagger-ui/dist/swagger.yaml  # Ensure YAML is copied

          # Fix Swagger UI config
          cat > swagger-ui/dist/swagger-initializer.js <<EOL
          window.onload = function() {
            window.ui = SwaggerUIBundle({
              url: 'swagger.yaml',
              dom_id: '#swagger-ui',
              deepLinking: true,
              presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
              ],
              layout: "StandaloneLayout"
            });
          };
          EOL

      - name: Verify Files Before Deployment
        run: ls -R swagger-ui/dist

      - name: Push `swagger-ui/dist/` to `gh-pages`
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          mv swagger-ui/dist/* .
          git add .
          git commit -m "Deploy Swagger UI"
          git push --force origin gh-pages
